// Code generated by protoc-gen-go.
// source: app.proto
// DO NOT EDIT!

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	app.proto
	common.proto
	hsm.proto
	network.proto

It has these top-level messages:
	Asset
	CreateAssetsRequest
	CreateAssetsResponse
	Account
	CreateAccountsRequest
	CreateAccountsResponse
	CreateControlProgramsRequest
	CreateControlProgramsResponse
	TxFeed
	TxFeedResponse
	CreateTxFeedRequest
	GetTxFeedRequest
	UpdateTxFeedRequest
	DeleteTxFeedRequest
	CreateAccessTokenRequest
	CreateAccessTokenResponse
	ListAccessTokensQuery
	ListAccessTokensResponse
	DeleteAccessTokenRequest
	AccessToken
	FilterParam
	ListAccountsQuery
	ListAccountsResponse
	ListAssetsQuery
	ListAssetsResponse
	ListBalancesQuery
	ListBalancesResponse
	ListTxFeedsQuery
	ListTxFeedsResponse
	ListTxsQuery
	ListTxsResponse
	ListUnspentOutputsQuery
	ListUnspentOutputsResponse
	Empty
	ErrorResponse
	Error
	XPub
	CreateKeyRequest
	CreateKeyResponse
	ListKeysQuery
	ListKeysResponse
	DeleteKeyRequest
	SubmitTxRequest
	SubmitTxResponse
	GetBlockRequest
	GetBlockResponse
	GetSnapshotRequest
	GetSnapshotResponse
	GetSnapshotInfoResponse
	GetBlockHeightResponse
	SignBlockRequest
	SignBlockResponse
*/
package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Asset struct {
	Id              string       `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Alias           string       `protobuf:"bytes,2,opt,name=alias" json:"alias,omitempty"`
	IssuanceProgram []byte       `protobuf:"bytes,3,opt,name=issuance_program,json=issuanceProgram,proto3" json:"issuance_program,omitempty"`
	Keys            []*Asset_Key `protobuf:"bytes,4,rep,name=keys" json:"keys,omitempty"`
	Quorum          int32        `protobuf:"varint,5,opt,name=quorum" json:"quorum,omitempty"`
	Definition      []byte       `protobuf:"bytes,6,opt,name=definition,proto3" json:"definition,omitempty"`
	Tags            []byte       `protobuf:"bytes,7,opt,name=tags,proto3" json:"tags,omitempty"`
	IsLocal         bool         `protobuf:"varint,8,opt,name=is_local,json=isLocal" json:"is_local,omitempty"`
}

func (m *Asset) Reset()                    { *m = Asset{} }
func (m *Asset) String() string            { return proto.CompactTextString(m) }
func (*Asset) ProtoMessage()               {}
func (*Asset) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Asset) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Asset) GetAlias() string {
	if m != nil {
		return m.Alias
	}
	return ""
}

func (m *Asset) GetIssuanceProgram() []byte {
	if m != nil {
		return m.IssuanceProgram
	}
	return nil
}

func (m *Asset) GetKeys() []*Asset_Key {
	if m != nil {
		return m.Keys
	}
	return nil
}

func (m *Asset) GetQuorum() int32 {
	if m != nil {
		return m.Quorum
	}
	return 0
}

func (m *Asset) GetDefinition() []byte {
	if m != nil {
		return m.Definition
	}
	return nil
}

func (m *Asset) GetTags() []byte {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *Asset) GetIsLocal() bool {
	if m != nil {
		return m.IsLocal
	}
	return false
}

type Asset_Key struct {
	RootXpub            []byte   `protobuf:"bytes,1,opt,name=root_xpub,json=rootXpub,proto3" json:"root_xpub,omitempty"`
	AssetPubkey         []byte   `protobuf:"bytes,2,opt,name=asset_pubkey,json=assetPubkey,proto3" json:"asset_pubkey,omitempty"`
	AssetDerivationPath [][]byte `protobuf:"bytes,3,rep,name=asset_derivation_path,json=assetDerivationPath,proto3" json:"asset_derivation_path,omitempty"`
}

func (m *Asset_Key) Reset()                    { *m = Asset_Key{} }
func (m *Asset_Key) String() string            { return proto.CompactTextString(m) }
func (*Asset_Key) ProtoMessage()               {}
func (*Asset_Key) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

func (m *Asset_Key) GetRootXpub() []byte {
	if m != nil {
		return m.RootXpub
	}
	return nil
}

func (m *Asset_Key) GetAssetPubkey() []byte {
	if m != nil {
		return m.AssetPubkey
	}
	return nil
}

func (m *Asset_Key) GetAssetDerivationPath() [][]byte {
	if m != nil {
		return m.AssetDerivationPath
	}
	return nil
}

type CreateAssetsRequest struct {
	Requests []*CreateAssetsRequest_Request `protobuf:"bytes,1,rep,name=requests" json:"requests,omitempty"`
}

func (m *CreateAssetsRequest) Reset()                    { *m = CreateAssetsRequest{} }
func (m *CreateAssetsRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateAssetsRequest) ProtoMessage()               {}
func (*CreateAssetsRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *CreateAssetsRequest) GetRequests() []*CreateAssetsRequest_Request {
	if m != nil {
		return m.Requests
	}
	return nil
}

type CreateAssetsRequest_Request struct {
	Alias       string   `protobuf:"bytes,1,opt,name=alias" json:"alias,omitempty"`
	RootXpubs   []string `protobuf:"bytes,2,rep,name=root_xpubs,json=rootXpubs" json:"root_xpubs,omitempty"`
	Quorum      int32    `protobuf:"varint,3,opt,name=quorum" json:"quorum,omitempty"`
	Definition  []byte   `protobuf:"bytes,4,opt,name=definition,proto3" json:"definition,omitempty"`
	Tags        []byte   `protobuf:"bytes,5,opt,name=tags,proto3" json:"tags,omitempty"`
	ClientToken string   `protobuf:"bytes,6,opt,name=client_token,json=clientToken" json:"client_token,omitempty"`
}

func (m *CreateAssetsRequest_Request) Reset()                    { *m = CreateAssetsRequest_Request{} }
func (m *CreateAssetsRequest_Request) String() string            { return proto.CompactTextString(m) }
func (*CreateAssetsRequest_Request) ProtoMessage()               {}
func (*CreateAssetsRequest_Request) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1, 0} }

func (m *CreateAssetsRequest_Request) GetAlias() string {
	if m != nil {
		return m.Alias
	}
	return ""
}

func (m *CreateAssetsRequest_Request) GetRootXpubs() []string {
	if m != nil {
		return m.RootXpubs
	}
	return nil
}

func (m *CreateAssetsRequest_Request) GetQuorum() int32 {
	if m != nil {
		return m.Quorum
	}
	return 0
}

func (m *CreateAssetsRequest_Request) GetDefinition() []byte {
	if m != nil {
		return m.Definition
	}
	return nil
}

func (m *CreateAssetsRequest_Request) GetTags() []byte {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *CreateAssetsRequest_Request) GetClientToken() string {
	if m != nil {
		return m.ClientToken
	}
	return ""
}

type CreateAssetsResponse struct {
	Responses []*CreateAssetsResponse_Response `protobuf:"bytes,1,rep,name=responses" json:"responses,omitempty"`
	Error     *Error                           `protobuf:"bytes,9,opt,name=error" json:"error,omitempty"`
}

func (m *CreateAssetsResponse) Reset()                    { *m = CreateAssetsResponse{} }
func (m *CreateAssetsResponse) String() string            { return proto.CompactTextString(m) }
func (*CreateAssetsResponse) ProtoMessage()               {}
func (*CreateAssetsResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *CreateAssetsResponse) GetResponses() []*CreateAssetsResponse_Response {
	if m != nil {
		return m.Responses
	}
	return nil
}

func (m *CreateAssetsResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

type CreateAssetsResponse_Response struct {
	Asset *Asset `protobuf:"bytes,1,opt,name=asset" json:"asset,omitempty"`
	Error *Error `protobuf:"bytes,9,opt,name=error" json:"error,omitempty"`
}

func (m *CreateAssetsResponse_Response) Reset()         { *m = CreateAssetsResponse_Response{} }
func (m *CreateAssetsResponse_Response) String() string { return proto.CompactTextString(m) }
func (*CreateAssetsResponse_Response) ProtoMessage()    {}
func (*CreateAssetsResponse_Response) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{2, 0}
}

func (m *CreateAssetsResponse_Response) GetAsset() *Asset {
	if m != nil {
		return m.Asset
	}
	return nil
}

func (m *CreateAssetsResponse_Response) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

type Account struct {
	Id     string         `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Alias  string         `protobuf:"bytes,2,opt,name=alias" json:"alias,omitempty"`
	Keys   []*Account_Key `protobuf:"bytes,3,rep,name=keys" json:"keys,omitempty"`
	Quorum int32          `protobuf:"varint,4,opt,name=quorum" json:"quorum,omitempty"`
	Tags   []byte         `protobuf:"bytes,5,opt,name=tags,proto3" json:"tags,omitempty"`
}

func (m *Account) Reset()                    { *m = Account{} }
func (m *Account) String() string            { return proto.CompactTextString(m) }
func (*Account) ProtoMessage()               {}
func (*Account) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *Account) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Account) GetAlias() string {
	if m != nil {
		return m.Alias
	}
	return ""
}

func (m *Account) GetKeys() []*Account_Key {
	if m != nil {
		return m.Keys
	}
	return nil
}

func (m *Account) GetQuorum() int32 {
	if m != nil {
		return m.Quorum
	}
	return 0
}

func (m *Account) GetTags() []byte {
	if m != nil {
		return m.Tags
	}
	return nil
}

type Account_Key struct {
	RootXpub              []byte   `protobuf:"bytes,1,opt,name=root_xpub,json=rootXpub,proto3" json:"root_xpub,omitempty"`
	AccountXpub           []byte   `protobuf:"bytes,2,opt,name=account_xpub,json=accountXpub,proto3" json:"account_xpub,omitempty"`
	AccountDerivationPath [][]byte `protobuf:"bytes,3,rep,name=account_derivation_path,json=accountDerivationPath,proto3" json:"account_derivation_path,omitempty"`
}

func (m *Account_Key) Reset()                    { *m = Account_Key{} }
func (m *Account_Key) String() string            { return proto.CompactTextString(m) }
func (*Account_Key) ProtoMessage()               {}
func (*Account_Key) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3, 0} }

func (m *Account_Key) GetRootXpub() []byte {
	if m != nil {
		return m.RootXpub
	}
	return nil
}

func (m *Account_Key) GetAccountXpub() []byte {
	if m != nil {
		return m.AccountXpub
	}
	return nil
}

func (m *Account_Key) GetAccountDerivationPath() [][]byte {
	if m != nil {
		return m.AccountDerivationPath
	}
	return nil
}

type CreateAccountsRequest struct {
	Requests []*CreateAccountsRequest_Request `protobuf:"bytes,1,rep,name=requests" json:"requests,omitempty"`
}

func (m *CreateAccountsRequest) Reset()                    { *m = CreateAccountsRequest{} }
func (m *CreateAccountsRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateAccountsRequest) ProtoMessage()               {}
func (*CreateAccountsRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *CreateAccountsRequest) GetRequests() []*CreateAccountsRequest_Request {
	if m != nil {
		return m.Requests
	}
	return nil
}

type CreateAccountsRequest_Request struct {
	RootXpubs   []string `protobuf:"bytes,1,rep,name=root_xpubs,json=rootXpubs" json:"root_xpubs,omitempty"`
	Quorum      int32    `protobuf:"varint,2,opt,name=quorum" json:"quorum,omitempty"`
	Alias       string   `protobuf:"bytes,3,opt,name=alias" json:"alias,omitempty"`
	Tags        []byte   `protobuf:"bytes,4,opt,name=tags,proto3" json:"tags,omitempty"`
	ClientToken string   `protobuf:"bytes,5,opt,name=client_token,json=clientToken" json:"client_token,omitempty"`
}

func (m *CreateAccountsRequest_Request) Reset()         { *m = CreateAccountsRequest_Request{} }
func (m *CreateAccountsRequest_Request) String() string { return proto.CompactTextString(m) }
func (*CreateAccountsRequest_Request) ProtoMessage()    {}
func (*CreateAccountsRequest_Request) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{4, 0}
}

func (m *CreateAccountsRequest_Request) GetRootXpubs() []string {
	if m != nil {
		return m.RootXpubs
	}
	return nil
}

func (m *CreateAccountsRequest_Request) GetQuorum() int32 {
	if m != nil {
		return m.Quorum
	}
	return 0
}

func (m *CreateAccountsRequest_Request) GetAlias() string {
	if m != nil {
		return m.Alias
	}
	return ""
}

func (m *CreateAccountsRequest_Request) GetTags() []byte {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *CreateAccountsRequest_Request) GetClientToken() string {
	if m != nil {
		return m.ClientToken
	}
	return ""
}

type CreateAccountsResponse struct {
	Responses []*CreateAccountsResponse_Response `protobuf:"bytes,1,rep,name=responses" json:"responses,omitempty"`
	Error     *Error                             `protobuf:"bytes,9,opt,name=error" json:"error,omitempty"`
}

func (m *CreateAccountsResponse) Reset()                    { *m = CreateAccountsResponse{} }
func (m *CreateAccountsResponse) String() string            { return proto.CompactTextString(m) }
func (*CreateAccountsResponse) ProtoMessage()               {}
func (*CreateAccountsResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *CreateAccountsResponse) GetResponses() []*CreateAccountsResponse_Response {
	if m != nil {
		return m.Responses
	}
	return nil
}

func (m *CreateAccountsResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

type CreateAccountsResponse_Response struct {
	Account *Account `protobuf:"bytes,1,opt,name=account" json:"account,omitempty"`
	Error   *Error   `protobuf:"bytes,9,opt,name=error" json:"error,omitempty"`
}

func (m *CreateAccountsResponse_Response) Reset()         { *m = CreateAccountsResponse_Response{} }
func (m *CreateAccountsResponse_Response) String() string { return proto.CompactTextString(m) }
func (*CreateAccountsResponse_Response) ProtoMessage()    {}
func (*CreateAccountsResponse_Response) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{5, 0}
}

func (m *CreateAccountsResponse_Response) GetAccount() *Account {
	if m != nil {
		return m.Account
	}
	return nil
}

func (m *CreateAccountsResponse_Response) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

type CreateControlProgramsRequest struct {
	Requests []*CreateControlProgramsRequest_Request `protobuf:"bytes,1,rep,name=requests" json:"requests,omitempty"`
}

func (m *CreateControlProgramsRequest) Reset()                    { *m = CreateControlProgramsRequest{} }
func (m *CreateControlProgramsRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateControlProgramsRequest) ProtoMessage()               {}
func (*CreateControlProgramsRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *CreateControlProgramsRequest) GetRequests() []*CreateControlProgramsRequest_Request {
	if m != nil {
		return m.Requests
	}
	return nil
}

type CreateControlProgramsRequest_Account struct {
	// Types that are valid to be assigned to Identifier:
	//	*CreateControlProgramsRequest_Account_AccountId
	//	*CreateControlProgramsRequest_Account_AccountAlias
	Identifier isCreateControlProgramsRequest_Account_Identifier `protobuf_oneof:"identifier"`
}

func (m *CreateControlProgramsRequest_Account) Reset()         { *m = CreateControlProgramsRequest_Account{} }
func (m *CreateControlProgramsRequest_Account) String() string { return proto.CompactTextString(m) }
func (*CreateControlProgramsRequest_Account) ProtoMessage()    {}
func (*CreateControlProgramsRequest_Account) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{6, 0}
}

type isCreateControlProgramsRequest_Account_Identifier interface {
	isCreateControlProgramsRequest_Account_Identifier()
}

type CreateControlProgramsRequest_Account_AccountId struct {
	AccountId string `protobuf:"bytes,1,opt,name=account_id,json=accountId,oneof"`
}
type CreateControlProgramsRequest_Account_AccountAlias struct {
	AccountAlias string `protobuf:"bytes,2,opt,name=account_alias,json=accountAlias,oneof"`
}

func (*CreateControlProgramsRequest_Account_AccountId) isCreateControlProgramsRequest_Account_Identifier() {
}
func (*CreateControlProgramsRequest_Account_AccountAlias) isCreateControlProgramsRequest_Account_Identifier() {
}

func (m *CreateControlProgramsRequest_Account) GetIdentifier() isCreateControlProgramsRequest_Account_Identifier {
	if m != nil {
		return m.Identifier
	}
	return nil
}

func (m *CreateControlProgramsRequest_Account) GetAccountId() string {
	if x, ok := m.GetIdentifier().(*CreateControlProgramsRequest_Account_AccountId); ok {
		return x.AccountId
	}
	return ""
}

func (m *CreateControlProgramsRequest_Account) GetAccountAlias() string {
	if x, ok := m.GetIdentifier().(*CreateControlProgramsRequest_Account_AccountAlias); ok {
		return x.AccountAlias
	}
	return ""
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*CreateControlProgramsRequest_Account) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _CreateControlProgramsRequest_Account_OneofMarshaler, _CreateControlProgramsRequest_Account_OneofUnmarshaler, _CreateControlProgramsRequest_Account_OneofSizer, []interface{}{
		(*CreateControlProgramsRequest_Account_AccountId)(nil),
		(*CreateControlProgramsRequest_Account_AccountAlias)(nil),
	}
}

func _CreateControlProgramsRequest_Account_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*CreateControlProgramsRequest_Account)
	// identifier
	switch x := m.Identifier.(type) {
	case *CreateControlProgramsRequest_Account_AccountId:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		b.EncodeStringBytes(x.AccountId)
	case *CreateControlProgramsRequest_Account_AccountAlias:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		b.EncodeStringBytes(x.AccountAlias)
	case nil:
	default:
		return fmt.Errorf("CreateControlProgramsRequest_Account.Identifier has unexpected type %T", x)
	}
	return nil
}

func _CreateControlProgramsRequest_Account_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*CreateControlProgramsRequest_Account)
	switch tag {
	case 1: // identifier.account_id
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.Identifier = &CreateControlProgramsRequest_Account_AccountId{x}
		return true, err
	case 2: // identifier.account_alias
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.Identifier = &CreateControlProgramsRequest_Account_AccountAlias{x}
		return true, err
	default:
		return false, nil
	}
}

func _CreateControlProgramsRequest_Account_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*CreateControlProgramsRequest_Account)
	// identifier
	switch x := m.Identifier.(type) {
	case *CreateControlProgramsRequest_Account_AccountId:
		n += proto.SizeVarint(1<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(len(x.AccountId)))
		n += len(x.AccountId)
	case *CreateControlProgramsRequest_Account_AccountAlias:
		n += proto.SizeVarint(2<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(len(x.AccountAlias)))
		n += len(x.AccountAlias)
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type CreateControlProgramsRequest_Request struct {
	// Types that are valid to be assigned to Type:
	//	*CreateControlProgramsRequest_Request_Account
	Type isCreateControlProgramsRequest_Request_Type `protobuf_oneof:"type"`
}

func (m *CreateControlProgramsRequest_Request) Reset()         { *m = CreateControlProgramsRequest_Request{} }
func (m *CreateControlProgramsRequest_Request) String() string { return proto.CompactTextString(m) }
func (*CreateControlProgramsRequest_Request) ProtoMessage()    {}
func (*CreateControlProgramsRequest_Request) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{6, 1}
}

type isCreateControlProgramsRequest_Request_Type interface {
	isCreateControlProgramsRequest_Request_Type()
}

type CreateControlProgramsRequest_Request_Account struct {
	Account *CreateControlProgramsRequest_Account `protobuf:"bytes,1,opt,name=account,oneof"`
}

func (*CreateControlProgramsRequest_Request_Account) isCreateControlProgramsRequest_Request_Type() {}

func (m *CreateControlProgramsRequest_Request) GetType() isCreateControlProgramsRequest_Request_Type {
	if m != nil {
		return m.Type
	}
	return nil
}

func (m *CreateControlProgramsRequest_Request) GetAccount() *CreateControlProgramsRequest_Account {
	if x, ok := m.GetType().(*CreateControlProgramsRequest_Request_Account); ok {
		return x.Account
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*CreateControlProgramsRequest_Request) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _CreateControlProgramsRequest_Request_OneofMarshaler, _CreateControlProgramsRequest_Request_OneofUnmarshaler, _CreateControlProgramsRequest_Request_OneofSizer, []interface{}{
		(*CreateControlProgramsRequest_Request_Account)(nil),
	}
}

func _CreateControlProgramsRequest_Request_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*CreateControlProgramsRequest_Request)
	// type
	switch x := m.Type.(type) {
	case *CreateControlProgramsRequest_Request_Account:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Account); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("CreateControlProgramsRequest_Request.Type has unexpected type %T", x)
	}
	return nil
}

func _CreateControlProgramsRequest_Request_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*CreateControlProgramsRequest_Request)
	switch tag {
	case 1: // type.account
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(CreateControlProgramsRequest_Account)
		err := b.DecodeMessage(msg)
		m.Type = &CreateControlProgramsRequest_Request_Account{msg}
		return true, err
	default:
		return false, nil
	}
}

func _CreateControlProgramsRequest_Request_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*CreateControlProgramsRequest_Request)
	// type
	switch x := m.Type.(type) {
	case *CreateControlProgramsRequest_Request_Account:
		s := proto.Size(x.Account)
		n += proto.SizeVarint(1<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type CreateControlProgramsResponse struct {
	Responses []*CreateControlProgramsResponse_Response `protobuf:"bytes,1,rep,name=responses" json:"responses,omitempty"`
	Error     *Error                                    `protobuf:"bytes,9,opt,name=error" json:"error,omitempty"`
}

func (m *CreateControlProgramsResponse) Reset()                    { *m = CreateControlProgramsResponse{} }
func (m *CreateControlProgramsResponse) String() string            { return proto.CompactTextString(m) }
func (*CreateControlProgramsResponse) ProtoMessage()               {}
func (*CreateControlProgramsResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *CreateControlProgramsResponse) GetResponses() []*CreateControlProgramsResponse_Response {
	if m != nil {
		return m.Responses
	}
	return nil
}

func (m *CreateControlProgramsResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

type CreateControlProgramsResponse_Response struct {
	ControlProgram []byte `protobuf:"bytes,1,opt,name=control_program,json=controlProgram,proto3" json:"control_program,omitempty"`
	Error          *Error `protobuf:"bytes,9,opt,name=error" json:"error,omitempty"`
}

func (m *CreateControlProgramsResponse_Response) Reset() {
	*m = CreateControlProgramsResponse_Response{}
}
func (m *CreateControlProgramsResponse_Response) String() string { return proto.CompactTextString(m) }
func (*CreateControlProgramsResponse_Response) ProtoMessage()    {}
func (*CreateControlProgramsResponse_Response) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{7, 0}
}

func (m *CreateControlProgramsResponse_Response) GetControlProgram() []byte {
	if m != nil {
		return m.ControlProgram
	}
	return nil
}

func (m *CreateControlProgramsResponse_Response) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

type TxFeed struct {
	Id     string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Alias  string `protobuf:"bytes,2,opt,name=alias" json:"alias,omitempty"`
	Filter string `protobuf:"bytes,3,opt,name=filter" json:"filter,omitempty"`
	After  string `protobuf:"bytes,4,opt,name=after" json:"after,omitempty"`
}

func (m *TxFeed) Reset()                    { *m = TxFeed{} }
func (m *TxFeed) String() string            { return proto.CompactTextString(m) }
func (*TxFeed) ProtoMessage()               {}
func (*TxFeed) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *TxFeed) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *TxFeed) GetAlias() string {
	if m != nil {
		return m.Alias
	}
	return ""
}

func (m *TxFeed) GetFilter() string {
	if m != nil {
		return m.Filter
	}
	return ""
}

func (m *TxFeed) GetAfter() string {
	if m != nil {
		return m.After
	}
	return ""
}

type TxFeedResponse struct {
	Response *TxFeed `protobuf:"bytes,1,opt,name=response" json:"response,omitempty"`
	Error    *Error  `protobuf:"bytes,9,opt,name=error" json:"error,omitempty"`
}

func (m *TxFeedResponse) Reset()                    { *m = TxFeedResponse{} }
func (m *TxFeedResponse) String() string            { return proto.CompactTextString(m) }
func (*TxFeedResponse) ProtoMessage()               {}
func (*TxFeedResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *TxFeedResponse) GetResponse() *TxFeed {
	if m != nil {
		return m.Response
	}
	return nil
}

func (m *TxFeedResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

type CreateTxFeedRequest struct {
	Alias       string `protobuf:"bytes,1,opt,name=alias" json:"alias,omitempty"`
	Filter      string `protobuf:"bytes,2,opt,name=filter" json:"filter,omitempty"`
	ClientToken string `protobuf:"bytes,3,opt,name=client_token,json=clientToken" json:"client_token,omitempty"`
}

func (m *CreateTxFeedRequest) Reset()                    { *m = CreateTxFeedRequest{} }
func (m *CreateTxFeedRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateTxFeedRequest) ProtoMessage()               {}
func (*CreateTxFeedRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *CreateTxFeedRequest) GetAlias() string {
	if m != nil {
		return m.Alias
	}
	return ""
}

func (m *CreateTxFeedRequest) GetFilter() string {
	if m != nil {
		return m.Filter
	}
	return ""
}

func (m *CreateTxFeedRequest) GetClientToken() string {
	if m != nil {
		return m.ClientToken
	}
	return ""
}

type GetTxFeedRequest struct {
	// Types that are valid to be assigned to Identifier:
	//	*GetTxFeedRequest_Id
	//	*GetTxFeedRequest_Alias
	Identifier isGetTxFeedRequest_Identifier `protobuf_oneof:"identifier"`
}

func (m *GetTxFeedRequest) Reset()                    { *m = GetTxFeedRequest{} }
func (m *GetTxFeedRequest) String() string            { return proto.CompactTextString(m) }
func (*GetTxFeedRequest) ProtoMessage()               {}
func (*GetTxFeedRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

type isGetTxFeedRequest_Identifier interface {
	isGetTxFeedRequest_Identifier()
}

type GetTxFeedRequest_Id struct {
	Id string `protobuf:"bytes,1,opt,name=id,oneof"`
}
type GetTxFeedRequest_Alias struct {
	Alias string `protobuf:"bytes,2,opt,name=alias,oneof"`
}

func (*GetTxFeedRequest_Id) isGetTxFeedRequest_Identifier()    {}
func (*GetTxFeedRequest_Alias) isGetTxFeedRequest_Identifier() {}

func (m *GetTxFeedRequest) GetIdentifier() isGetTxFeedRequest_Identifier {
	if m != nil {
		return m.Identifier
	}
	return nil
}

func (m *GetTxFeedRequest) GetId() string {
	if x, ok := m.GetIdentifier().(*GetTxFeedRequest_Id); ok {
		return x.Id
	}
	return ""
}

func (m *GetTxFeedRequest) GetAlias() string {
	if x, ok := m.GetIdentifier().(*GetTxFeedRequest_Alias); ok {
		return x.Alias
	}
	return ""
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*GetTxFeedRequest) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _GetTxFeedRequest_OneofMarshaler, _GetTxFeedRequest_OneofUnmarshaler, _GetTxFeedRequest_OneofSizer, []interface{}{
		(*GetTxFeedRequest_Id)(nil),
		(*GetTxFeedRequest_Alias)(nil),
	}
}

func _GetTxFeedRequest_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*GetTxFeedRequest)
	// identifier
	switch x := m.Identifier.(type) {
	case *GetTxFeedRequest_Id:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		b.EncodeStringBytes(x.Id)
	case *GetTxFeedRequest_Alias:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		b.EncodeStringBytes(x.Alias)
	case nil:
	default:
		return fmt.Errorf("GetTxFeedRequest.Identifier has unexpected type %T", x)
	}
	return nil
}

func _GetTxFeedRequest_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*GetTxFeedRequest)
	switch tag {
	case 1: // identifier.id
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.Identifier = &GetTxFeedRequest_Id{x}
		return true, err
	case 2: // identifier.alias
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.Identifier = &GetTxFeedRequest_Alias{x}
		return true, err
	default:
		return false, nil
	}
}

func _GetTxFeedRequest_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*GetTxFeedRequest)
	// identifier
	switch x := m.Identifier.(type) {
	case *GetTxFeedRequest_Id:
		n += proto.SizeVarint(1<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(len(x.Id)))
		n += len(x.Id)
	case *GetTxFeedRequest_Alias:
		n += proto.SizeVarint(2<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(len(x.Alias)))
		n += len(x.Alias)
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type UpdateTxFeedRequest struct {
	// Types that are valid to be assigned to Identifier:
	//	*UpdateTxFeedRequest_Id
	//	*UpdateTxFeedRequest_Alias
	Identifier    isUpdateTxFeedRequest_Identifier `protobuf_oneof:"identifier"`
	PreviousAfter string                           `protobuf:"bytes,3,opt,name=previous_after,json=previousAfter" json:"previous_after,omitempty"`
	After         string                           `protobuf:"bytes,4,opt,name=after" json:"after,omitempty"`
}

func (m *UpdateTxFeedRequest) Reset()                    { *m = UpdateTxFeedRequest{} }
func (m *UpdateTxFeedRequest) String() string            { return proto.CompactTextString(m) }
func (*UpdateTxFeedRequest) ProtoMessage()               {}
func (*UpdateTxFeedRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

type isUpdateTxFeedRequest_Identifier interface {
	isUpdateTxFeedRequest_Identifier()
}

type UpdateTxFeedRequest_Id struct {
	Id string `protobuf:"bytes,1,opt,name=id,oneof"`
}
type UpdateTxFeedRequest_Alias struct {
	Alias string `protobuf:"bytes,2,opt,name=alias,oneof"`
}

func (*UpdateTxFeedRequest_Id) isUpdateTxFeedRequest_Identifier()    {}
func (*UpdateTxFeedRequest_Alias) isUpdateTxFeedRequest_Identifier() {}

func (m *UpdateTxFeedRequest) GetIdentifier() isUpdateTxFeedRequest_Identifier {
	if m != nil {
		return m.Identifier
	}
	return nil
}

func (m *UpdateTxFeedRequest) GetId() string {
	if x, ok := m.GetIdentifier().(*UpdateTxFeedRequest_Id); ok {
		return x.Id
	}
	return ""
}

func (m *UpdateTxFeedRequest) GetAlias() string {
	if x, ok := m.GetIdentifier().(*UpdateTxFeedRequest_Alias); ok {
		return x.Alias
	}
	return ""
}

func (m *UpdateTxFeedRequest) GetPreviousAfter() string {
	if m != nil {
		return m.PreviousAfter
	}
	return ""
}

func (m *UpdateTxFeedRequest) GetAfter() string {
	if m != nil {
		return m.After
	}
	return ""
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*UpdateTxFeedRequest) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _UpdateTxFeedRequest_OneofMarshaler, _UpdateTxFeedRequest_OneofUnmarshaler, _UpdateTxFeedRequest_OneofSizer, []interface{}{
		(*UpdateTxFeedRequest_Id)(nil),
		(*UpdateTxFeedRequest_Alias)(nil),
	}
}

func _UpdateTxFeedRequest_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*UpdateTxFeedRequest)
	// identifier
	switch x := m.Identifier.(type) {
	case *UpdateTxFeedRequest_Id:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		b.EncodeStringBytes(x.Id)
	case *UpdateTxFeedRequest_Alias:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		b.EncodeStringBytes(x.Alias)
	case nil:
	default:
		return fmt.Errorf("UpdateTxFeedRequest.Identifier has unexpected type %T", x)
	}
	return nil
}

func _UpdateTxFeedRequest_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*UpdateTxFeedRequest)
	switch tag {
	case 1: // identifier.id
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.Identifier = &UpdateTxFeedRequest_Id{x}
		return true, err
	case 2: // identifier.alias
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.Identifier = &UpdateTxFeedRequest_Alias{x}
		return true, err
	default:
		return false, nil
	}
}

func _UpdateTxFeedRequest_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*UpdateTxFeedRequest)
	// identifier
	switch x := m.Identifier.(type) {
	case *UpdateTxFeedRequest_Id:
		n += proto.SizeVarint(1<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(len(x.Id)))
		n += len(x.Id)
	case *UpdateTxFeedRequest_Alias:
		n += proto.SizeVarint(2<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(len(x.Alias)))
		n += len(x.Alias)
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type DeleteTxFeedRequest struct {
	// Types that are valid to be assigned to Identifier:
	//	*DeleteTxFeedRequest_Id
	//	*DeleteTxFeedRequest_Alias
	Identifier isDeleteTxFeedRequest_Identifier `protobuf_oneof:"identifier"`
}

func (m *DeleteTxFeedRequest) Reset()                    { *m = DeleteTxFeedRequest{} }
func (m *DeleteTxFeedRequest) String() string            { return proto.CompactTextString(m) }
func (*DeleteTxFeedRequest) ProtoMessage()               {}
func (*DeleteTxFeedRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

type isDeleteTxFeedRequest_Identifier interface {
	isDeleteTxFeedRequest_Identifier()
}

type DeleteTxFeedRequest_Id struct {
	Id string `protobuf:"bytes,1,opt,name=id,oneof"`
}
type DeleteTxFeedRequest_Alias struct {
	Alias string `protobuf:"bytes,2,opt,name=alias,oneof"`
}

func (*DeleteTxFeedRequest_Id) isDeleteTxFeedRequest_Identifier()    {}
func (*DeleteTxFeedRequest_Alias) isDeleteTxFeedRequest_Identifier() {}

func (m *DeleteTxFeedRequest) GetIdentifier() isDeleteTxFeedRequest_Identifier {
	if m != nil {
		return m.Identifier
	}
	return nil
}

func (m *DeleteTxFeedRequest) GetId() string {
	if x, ok := m.GetIdentifier().(*DeleteTxFeedRequest_Id); ok {
		return x.Id
	}
	return ""
}

func (m *DeleteTxFeedRequest) GetAlias() string {
	if x, ok := m.GetIdentifier().(*DeleteTxFeedRequest_Alias); ok {
		return x.Alias
	}
	return ""
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*DeleteTxFeedRequest) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _DeleteTxFeedRequest_OneofMarshaler, _DeleteTxFeedRequest_OneofUnmarshaler, _DeleteTxFeedRequest_OneofSizer, []interface{}{
		(*DeleteTxFeedRequest_Id)(nil),
		(*DeleteTxFeedRequest_Alias)(nil),
	}
}

func _DeleteTxFeedRequest_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*DeleteTxFeedRequest)
	// identifier
	switch x := m.Identifier.(type) {
	case *DeleteTxFeedRequest_Id:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		b.EncodeStringBytes(x.Id)
	case *DeleteTxFeedRequest_Alias:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		b.EncodeStringBytes(x.Alias)
	case nil:
	default:
		return fmt.Errorf("DeleteTxFeedRequest.Identifier has unexpected type %T", x)
	}
	return nil
}

func _DeleteTxFeedRequest_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*DeleteTxFeedRequest)
	switch tag {
	case 1: // identifier.id
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.Identifier = &DeleteTxFeedRequest_Id{x}
		return true, err
	case 2: // identifier.alias
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.Identifier = &DeleteTxFeedRequest_Alias{x}
		return true, err
	default:
		return false, nil
	}
}

func _DeleteTxFeedRequest_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*DeleteTxFeedRequest)
	// identifier
	switch x := m.Identifier.(type) {
	case *DeleteTxFeedRequest_Id:
		n += proto.SizeVarint(1<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(len(x.Id)))
		n += len(x.Id)
	case *DeleteTxFeedRequest_Alias:
		n += proto.SizeVarint(2<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(len(x.Alias)))
		n += len(x.Alias)
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type CreateAccessTokenRequest struct {
	Id   string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Type string `protobuf:"bytes,2,opt,name=type" json:"type,omitempty"`
}

func (m *CreateAccessTokenRequest) Reset()                    { *m = CreateAccessTokenRequest{} }
func (m *CreateAccessTokenRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateAccessTokenRequest) ProtoMessage()               {}
func (*CreateAccessTokenRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

func (m *CreateAccessTokenRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *CreateAccessTokenRequest) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

type CreateAccessTokenResponse struct {
	Token *AccessToken `protobuf:"bytes,1,opt,name=token" json:"token,omitempty"`
	Error *Error       `protobuf:"bytes,9,opt,name=error" json:"error,omitempty"`
}

func (m *CreateAccessTokenResponse) Reset()                    { *m = CreateAccessTokenResponse{} }
func (m *CreateAccessTokenResponse) String() string            { return proto.CompactTextString(m) }
func (*CreateAccessTokenResponse) ProtoMessage()               {}
func (*CreateAccessTokenResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

func (m *CreateAccessTokenResponse) GetToken() *AccessToken {
	if m != nil {
		return m.Token
	}
	return nil
}

func (m *CreateAccessTokenResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

type ListAccessTokensQuery struct {
	Type     string `protobuf:"bytes,1,opt,name=type" json:"type,omitempty"`
	PageSize int32  `protobuf:"varint,2,opt,name=page_size,json=pageSize" json:"page_size,omitempty"`
	After    string `protobuf:"bytes,3,opt,name=after" json:"after,omitempty"`
}

func (m *ListAccessTokensQuery) Reset()                    { *m = ListAccessTokensQuery{} }
func (m *ListAccessTokensQuery) String() string            { return proto.CompactTextString(m) }
func (*ListAccessTokensQuery) ProtoMessage()               {}
func (*ListAccessTokensQuery) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{16} }

func (m *ListAccessTokensQuery) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *ListAccessTokensQuery) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *ListAccessTokensQuery) GetAfter() string {
	if m != nil {
		return m.After
	}
	return ""
}

type ListAccessTokensResponse struct {
	Items    []*AccessToken         `protobuf:"bytes,1,rep,name=items" json:"items,omitempty"`
	LastPage bool                   `protobuf:"varint,2,opt,name=last_page,json=lastPage" json:"last_page,omitempty"`
	Next     *ListAccessTokensQuery `protobuf:"bytes,3,opt,name=next" json:"next,omitempty"`
	Error    *Error                 `protobuf:"bytes,9,opt,name=error" json:"error,omitempty"`
}

func (m *ListAccessTokensResponse) Reset()                    { *m = ListAccessTokensResponse{} }
func (m *ListAccessTokensResponse) String() string            { return proto.CompactTextString(m) }
func (*ListAccessTokensResponse) ProtoMessage()               {}
func (*ListAccessTokensResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{17} }

func (m *ListAccessTokensResponse) GetItems() []*AccessToken {
	if m != nil {
		return m.Items
	}
	return nil
}

func (m *ListAccessTokensResponse) GetLastPage() bool {
	if m != nil {
		return m.LastPage
	}
	return false
}

func (m *ListAccessTokensResponse) GetNext() *ListAccessTokensQuery {
	if m != nil {
		return m.Next
	}
	return nil
}

func (m *ListAccessTokensResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

type DeleteAccessTokenRequest struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *DeleteAccessTokenRequest) Reset()                    { *m = DeleteAccessTokenRequest{} }
func (m *DeleteAccessTokenRequest) String() string            { return proto.CompactTextString(m) }
func (*DeleteAccessTokenRequest) ProtoMessage()               {}
func (*DeleteAccessTokenRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{18} }

func (m *DeleteAccessTokenRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type AccessToken struct {
	Id        string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Token     string `protobuf:"bytes,2,opt,name=token" json:"token,omitempty"`
	Type      string `protobuf:"bytes,3,opt,name=type" json:"type,omitempty"`
	CreatedAt string `protobuf:"bytes,4,opt,name=created_at,json=createdAt" json:"created_at,omitempty"`
}

func (m *AccessToken) Reset()                    { *m = AccessToken{} }
func (m *AccessToken) String() string            { return proto.CompactTextString(m) }
func (*AccessToken) ProtoMessage()               {}
func (*AccessToken) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{19} }

func (m *AccessToken) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *AccessToken) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *AccessToken) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *AccessToken) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

type FilterParam struct {
	// Types that are valid to be assigned to Value:
	//	*FilterParam_String_
	//	*FilterParam_Int64
	//	*FilterParam_Bytes
	//	*FilterParam_Bool
	Value isFilterParam_Value `protobuf_oneof:"value"`
}

func (m *FilterParam) Reset()                    { *m = FilterParam{} }
func (m *FilterParam) String() string            { return proto.CompactTextString(m) }
func (*FilterParam) ProtoMessage()               {}
func (*FilterParam) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{20} }

type isFilterParam_Value interface {
	isFilterParam_Value()
}

type FilterParam_String_ struct {
	String_ string `protobuf:"bytes,1,opt,name=string,oneof"`
}
type FilterParam_Int64 struct {
	Int64 int64 `protobuf:"varint,2,opt,name=int64,oneof"`
}
type FilterParam_Bytes struct {
	Bytes []byte `protobuf:"bytes,3,opt,name=bytes,proto3,oneof"`
}
type FilterParam_Bool struct {
	Bool bool `protobuf:"varint,4,opt,name=bool,oneof"`
}

func (*FilterParam_String_) isFilterParam_Value() {}
func (*FilterParam_Int64) isFilterParam_Value()   {}
func (*FilterParam_Bytes) isFilterParam_Value()   {}
func (*FilterParam_Bool) isFilterParam_Value()    {}

func (m *FilterParam) GetValue() isFilterParam_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *FilterParam) GetString_() string {
	if x, ok := m.GetValue().(*FilterParam_String_); ok {
		return x.String_
	}
	return ""
}

func (m *FilterParam) GetInt64() int64 {
	if x, ok := m.GetValue().(*FilterParam_Int64); ok {
		return x.Int64
	}
	return 0
}

func (m *FilterParam) GetBytes() []byte {
	if x, ok := m.GetValue().(*FilterParam_Bytes); ok {
		return x.Bytes
	}
	return nil
}

func (m *FilterParam) GetBool() bool {
	if x, ok := m.GetValue().(*FilterParam_Bool); ok {
		return x.Bool
	}
	return false
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*FilterParam) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _FilterParam_OneofMarshaler, _FilterParam_OneofUnmarshaler, _FilterParam_OneofSizer, []interface{}{
		(*FilterParam_String_)(nil),
		(*FilterParam_Int64)(nil),
		(*FilterParam_Bytes)(nil),
		(*FilterParam_Bool)(nil),
	}
}

func _FilterParam_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*FilterParam)
	// value
	switch x := m.Value.(type) {
	case *FilterParam_String_:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		b.EncodeStringBytes(x.String_)
	case *FilterParam_Int64:
		b.EncodeVarint(2<<3 | proto.WireVarint)
		b.EncodeVarint(uint64(x.Int64))
	case *FilterParam_Bytes:
		b.EncodeVarint(3<<3 | proto.WireBytes)
		b.EncodeRawBytes(x.Bytes)
	case *FilterParam_Bool:
		t := uint64(0)
		if x.Bool {
			t = 1
		}
		b.EncodeVarint(4<<3 | proto.WireVarint)
		b.EncodeVarint(t)
	case nil:
	default:
		return fmt.Errorf("FilterParam.Value has unexpected type %T", x)
	}
	return nil
}

func _FilterParam_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*FilterParam)
	switch tag {
	case 1: // value.string
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.Value = &FilterParam_String_{x}
		return true, err
	case 2: // value.int64
		if wire != proto.WireVarint {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeVarint()
		m.Value = &FilterParam_Int64{int64(x)}
		return true, err
	case 3: // value.bytes
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeRawBytes(true)
		m.Value = &FilterParam_Bytes{x}
		return true, err
	case 4: // value.bool
		if wire != proto.WireVarint {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeVarint()
		m.Value = &FilterParam_Bool{x != 0}
		return true, err
	default:
		return false, nil
	}
}

func _FilterParam_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*FilterParam)
	// value
	switch x := m.Value.(type) {
	case *FilterParam_String_:
		n += proto.SizeVarint(1<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(len(x.String_)))
		n += len(x.String_)
	case *FilterParam_Int64:
		n += proto.SizeVarint(2<<3 | proto.WireVarint)
		n += proto.SizeVarint(uint64(x.Int64))
	case *FilterParam_Bytes:
		n += proto.SizeVarint(3<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(len(x.Bytes)))
		n += len(x.Bytes)
	case *FilterParam_Bool:
		n += proto.SizeVarint(4<<3 | proto.WireVarint)
		n += 1
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type ListAccountsQuery struct {
	Filter       string         `protobuf:"bytes,1,opt,name=filter" json:"filter,omitempty"`
	FilterParams []*FilterParam `protobuf:"bytes,2,rep,name=filter_params,json=filterParams" json:"filter_params,omitempty"`
	After        string         `protobuf:"bytes,3,opt,name=after" json:"after,omitempty"`
}

func (m *ListAccountsQuery) Reset()                    { *m = ListAccountsQuery{} }
func (m *ListAccountsQuery) String() string            { return proto.CompactTextString(m) }
func (*ListAccountsQuery) ProtoMessage()               {}
func (*ListAccountsQuery) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{21} }

func (m *ListAccountsQuery) GetFilter() string {
	if m != nil {
		return m.Filter
	}
	return ""
}

func (m *ListAccountsQuery) GetFilterParams() []*FilterParam {
	if m != nil {
		return m.FilterParams
	}
	return nil
}

func (m *ListAccountsQuery) GetAfter() string {
	if m != nil {
		return m.After
	}
	return ""
}

type ListAccountsResponse struct {
	Items    []byte             `protobuf:"bytes,1,opt,name=items,proto3" json:"items,omitempty"`
	LastPage bool               `protobuf:"varint,2,opt,name=last_page,json=lastPage" json:"last_page,omitempty"`
	Next     *ListAccountsQuery `protobuf:"bytes,3,opt,name=next" json:"next,omitempty"`
	Error    *Error             `protobuf:"bytes,9,opt,name=error" json:"error,omitempty"`
}

func (m *ListAccountsResponse) Reset()                    { *m = ListAccountsResponse{} }
func (m *ListAccountsResponse) String() string            { return proto.CompactTextString(m) }
func (*ListAccountsResponse) ProtoMessage()               {}
func (*ListAccountsResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{22} }

func (m *ListAccountsResponse) GetItems() []byte {
	if m != nil {
		return m.Items
	}
	return nil
}

func (m *ListAccountsResponse) GetLastPage() bool {
	if m != nil {
		return m.LastPage
	}
	return false
}

func (m *ListAccountsResponse) GetNext() *ListAccountsQuery {
	if m != nil {
		return m.Next
	}
	return nil
}

func (m *ListAccountsResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

type ListAssetsQuery struct {
	Filter       string         `protobuf:"bytes,1,opt,name=filter" json:"filter,omitempty"`
	FilterParams []*FilterParam `protobuf:"bytes,2,rep,name=filter_params,json=filterParams" json:"filter_params,omitempty"`
	After        string         `protobuf:"bytes,3,opt,name=after" json:"after,omitempty"`
}

func (m *ListAssetsQuery) Reset()                    { *m = ListAssetsQuery{} }
func (m *ListAssetsQuery) String() string            { return proto.CompactTextString(m) }
func (*ListAssetsQuery) ProtoMessage()               {}
func (*ListAssetsQuery) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{23} }

func (m *ListAssetsQuery) GetFilter() string {
	if m != nil {
		return m.Filter
	}
	return ""
}

func (m *ListAssetsQuery) GetFilterParams() []*FilterParam {
	if m != nil {
		return m.FilterParams
	}
	return nil
}

func (m *ListAssetsQuery) GetAfter() string {
	if m != nil {
		return m.After
	}
	return ""
}

type ListAssetsResponse struct {
	Items    []byte           `protobuf:"bytes,1,opt,name=items,proto3" json:"items,omitempty"`
	LastPage bool             `protobuf:"varint,2,opt,name=last_page,json=lastPage" json:"last_page,omitempty"`
	Next     *ListAssetsQuery `protobuf:"bytes,3,opt,name=next" json:"next,omitempty"`
	Error    *Error           `protobuf:"bytes,9,opt,name=error" json:"error,omitempty"`
}

func (m *ListAssetsResponse) Reset()                    { *m = ListAssetsResponse{} }
func (m *ListAssetsResponse) String() string            { return proto.CompactTextString(m) }
func (*ListAssetsResponse) ProtoMessage()               {}
func (*ListAssetsResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{24} }

func (m *ListAssetsResponse) GetItems() []byte {
	if m != nil {
		return m.Items
	}
	return nil
}

func (m *ListAssetsResponse) GetLastPage() bool {
	if m != nil {
		return m.LastPage
	}
	return false
}

func (m *ListAssetsResponse) GetNext() *ListAssetsQuery {
	if m != nil {
		return m.Next
	}
	return nil
}

func (m *ListAssetsResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

type ListBalancesQuery struct {
	Filter       string         `protobuf:"bytes,1,opt,name=filter" json:"filter,omitempty"`
	FilterParams []*FilterParam `protobuf:"bytes,2,rep,name=filter_params,json=filterParams" json:"filter_params,omitempty"`
	SumBy        []string       `protobuf:"bytes,3,rep,name=sum_by,json=sumBy" json:"sum_by,omitempty"`
	Timestamp    uint64         `protobuf:"varint,4,opt,name=timestamp" json:"timestamp,omitempty"`
}

func (m *ListBalancesQuery) Reset()                    { *m = ListBalancesQuery{} }
func (m *ListBalancesQuery) String() string            { return proto.CompactTextString(m) }
func (*ListBalancesQuery) ProtoMessage()               {}
func (*ListBalancesQuery) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{25} }

func (m *ListBalancesQuery) GetFilter() string {
	if m != nil {
		return m.Filter
	}
	return ""
}

func (m *ListBalancesQuery) GetFilterParams() []*FilterParam {
	if m != nil {
		return m.FilterParams
	}
	return nil
}

func (m *ListBalancesQuery) GetSumBy() []string {
	if m != nil {
		return m.SumBy
	}
	return nil
}

func (m *ListBalancesQuery) GetTimestamp() uint64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

type ListBalancesResponse struct {
	Items    []byte             `protobuf:"bytes,1,opt,name=items,proto3" json:"items,omitempty"`
	LastPage bool               `protobuf:"varint,2,opt,name=last_page,json=lastPage" json:"last_page,omitempty"`
	Next     *ListBalancesQuery `protobuf:"bytes,3,opt,name=next" json:"next,omitempty"`
	Error    *Error             `protobuf:"bytes,9,opt,name=error" json:"error,omitempty"`
}

func (m *ListBalancesResponse) Reset()                    { *m = ListBalancesResponse{} }
func (m *ListBalancesResponse) String() string            { return proto.CompactTextString(m) }
func (*ListBalancesResponse) ProtoMessage()               {}
func (*ListBalancesResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{26} }

func (m *ListBalancesResponse) GetItems() []byte {
	if m != nil {
		return m.Items
	}
	return nil
}

func (m *ListBalancesResponse) GetLastPage() bool {
	if m != nil {
		return m.LastPage
	}
	return false
}

func (m *ListBalancesResponse) GetNext() *ListBalancesQuery {
	if m != nil {
		return m.Next
	}
	return nil
}

func (m *ListBalancesResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

type ListTxFeedsQuery struct {
	After string `protobuf:"bytes,1,opt,name=after" json:"after,omitempty"`
}

func (m *ListTxFeedsQuery) Reset()                    { *m = ListTxFeedsQuery{} }
func (m *ListTxFeedsQuery) String() string            { return proto.CompactTextString(m) }
func (*ListTxFeedsQuery) ProtoMessage()               {}
func (*ListTxFeedsQuery) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{27} }

func (m *ListTxFeedsQuery) GetAfter() string {
	if m != nil {
		return m.After
	}
	return ""
}

type ListTxFeedsResponse struct {
	Items    []*TxFeed         `protobuf:"bytes,1,rep,name=items" json:"items,omitempty"`
	LastPage bool              `protobuf:"varint,2,opt,name=last_page,json=lastPage" json:"last_page,omitempty"`
	Next     *ListTxFeedsQuery `protobuf:"bytes,3,opt,name=next" json:"next,omitempty"`
	Error    *Error            `protobuf:"bytes,9,opt,name=error" json:"error,omitempty"`
}

func (m *ListTxFeedsResponse) Reset()                    { *m = ListTxFeedsResponse{} }
func (m *ListTxFeedsResponse) String() string            { return proto.CompactTextString(m) }
func (*ListTxFeedsResponse) ProtoMessage()               {}
func (*ListTxFeedsResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{28} }

func (m *ListTxFeedsResponse) GetItems() []*TxFeed {
	if m != nil {
		return m.Items
	}
	return nil
}

func (m *ListTxFeedsResponse) GetLastPage() bool {
	if m != nil {
		return m.LastPage
	}
	return false
}

func (m *ListTxFeedsResponse) GetNext() *ListTxFeedsQuery {
	if m != nil {
		return m.Next
	}
	return nil
}

func (m *ListTxFeedsResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

type ListTxsQuery struct {
	Filter                string         `protobuf:"bytes,1,opt,name=filter" json:"filter,omitempty"`
	FilterParams          []*FilterParam `protobuf:"bytes,2,rep,name=filter_params,json=filterParams" json:"filter_params,omitempty"`
	AscendingWithLongPoll bool           `protobuf:"varint,3,opt,name=ascending_with_long_poll,json=ascendingWithLongPoll" json:"ascending_with_long_poll,omitempty"`
	Timeout               string         `protobuf:"bytes,4,opt,name=timeout" json:"timeout,omitempty"`
	StartTime             uint64         `protobuf:"varint,5,opt,name=start_time,json=startTime" json:"start_time,omitempty"`
	EndTime               uint64         `protobuf:"varint,6,opt,name=end_time,json=endTime" json:"end_time,omitempty"`
	After                 string         `protobuf:"bytes,7,opt,name=after" json:"after,omitempty"`
}

func (m *ListTxsQuery) Reset()                    { *m = ListTxsQuery{} }
func (m *ListTxsQuery) String() string            { return proto.CompactTextString(m) }
func (*ListTxsQuery) ProtoMessage()               {}
func (*ListTxsQuery) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{29} }

func (m *ListTxsQuery) GetFilter() string {
	if m != nil {
		return m.Filter
	}
	return ""
}

func (m *ListTxsQuery) GetFilterParams() []*FilterParam {
	if m != nil {
		return m.FilterParams
	}
	return nil
}

func (m *ListTxsQuery) GetAscendingWithLongPoll() bool {
	if m != nil {
		return m.AscendingWithLongPoll
	}
	return false
}

func (m *ListTxsQuery) GetTimeout() string {
	if m != nil {
		return m.Timeout
	}
	return ""
}

func (m *ListTxsQuery) GetStartTime() uint64 {
	if m != nil {
		return m.StartTime
	}
	return 0
}

func (m *ListTxsQuery) GetEndTime() uint64 {
	if m != nil {
		return m.EndTime
	}
	return 0
}

func (m *ListTxsQuery) GetAfter() string {
	if m != nil {
		return m.After
	}
	return ""
}

type ListTxsResponse struct {
	Items    []byte        `protobuf:"bytes,1,opt,name=items,proto3" json:"items,omitempty"`
	LastPage bool          `protobuf:"varint,2,opt,name=last_page,json=lastPage" json:"last_page,omitempty"`
	Next     *ListTxsQuery `protobuf:"bytes,3,opt,name=next" json:"next,omitempty"`
	Error    *Error        `protobuf:"bytes,9,opt,name=error" json:"error,omitempty"`
}

func (m *ListTxsResponse) Reset()                    { *m = ListTxsResponse{} }
func (m *ListTxsResponse) String() string            { return proto.CompactTextString(m) }
func (*ListTxsResponse) ProtoMessage()               {}
func (*ListTxsResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{30} }

func (m *ListTxsResponse) GetItems() []byte {
	if m != nil {
		return m.Items
	}
	return nil
}

func (m *ListTxsResponse) GetLastPage() bool {
	if m != nil {
		return m.LastPage
	}
	return false
}

func (m *ListTxsResponse) GetNext() *ListTxsQuery {
	if m != nil {
		return m.Next
	}
	return nil
}

func (m *ListTxsResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

type ListUnspentOutputsQuery struct {
	Filter       string         `protobuf:"bytes,1,opt,name=filter" json:"filter,omitempty"`
	FilterParams []*FilterParam `protobuf:"bytes,2,rep,name=filter_params,json=filterParams" json:"filter_params,omitempty"`
	After        string         `protobuf:"bytes,3,opt,name=after" json:"after,omitempty"`
	Timestamp    uint64         `protobuf:"varint,4,opt,name=timestamp" json:"timestamp,omitempty"`
}

func (m *ListUnspentOutputsQuery) Reset()                    { *m = ListUnspentOutputsQuery{} }
func (m *ListUnspentOutputsQuery) String() string            { return proto.CompactTextString(m) }
func (*ListUnspentOutputsQuery) ProtoMessage()               {}
func (*ListUnspentOutputsQuery) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{31} }

func (m *ListUnspentOutputsQuery) GetFilter() string {
	if m != nil {
		return m.Filter
	}
	return ""
}

func (m *ListUnspentOutputsQuery) GetFilterParams() []*FilterParam {
	if m != nil {
		return m.FilterParams
	}
	return nil
}

func (m *ListUnspentOutputsQuery) GetAfter() string {
	if m != nil {
		return m.After
	}
	return ""
}

func (m *ListUnspentOutputsQuery) GetTimestamp() uint64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

type ListUnspentOutputsResponse struct {
	Items    []byte                   `protobuf:"bytes,1,opt,name=items,proto3" json:"items,omitempty"`
	LastPage bool                     `protobuf:"varint,2,opt,name=last_page,json=lastPage" json:"last_page,omitempty"`
	Next     *ListUnspentOutputsQuery `protobuf:"bytes,3,opt,name=next" json:"next,omitempty"`
	Error    *Error                   `protobuf:"bytes,9,opt,name=error" json:"error,omitempty"`
}

func (m *ListUnspentOutputsResponse) Reset()                    { *m = ListUnspentOutputsResponse{} }
func (m *ListUnspentOutputsResponse) String() string            { return proto.CompactTextString(m) }
func (*ListUnspentOutputsResponse) ProtoMessage()               {}
func (*ListUnspentOutputsResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{32} }

func (m *ListUnspentOutputsResponse) GetItems() []byte {
	if m != nil {
		return m.Items
	}
	return nil
}

func (m *ListUnspentOutputsResponse) GetLastPage() bool {
	if m != nil {
		return m.LastPage
	}
	return false
}

func (m *ListUnspentOutputsResponse) GetNext() *ListUnspentOutputsQuery {
	if m != nil {
		return m.Next
	}
	return nil
}

func (m *ListUnspentOutputsResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func init() {
	proto.RegisterType((*Asset)(nil), "pb.Asset")
	proto.RegisterType((*Asset_Key)(nil), "pb.Asset.Key")
	proto.RegisterType((*CreateAssetsRequest)(nil), "pb.CreateAssetsRequest")
	proto.RegisterType((*CreateAssetsRequest_Request)(nil), "pb.CreateAssetsRequest.Request")
	proto.RegisterType((*CreateAssetsResponse)(nil), "pb.CreateAssetsResponse")
	proto.RegisterType((*CreateAssetsResponse_Response)(nil), "pb.CreateAssetsResponse.Response")
	proto.RegisterType((*Account)(nil), "pb.Account")
	proto.RegisterType((*Account_Key)(nil), "pb.Account.Key")
	proto.RegisterType((*CreateAccountsRequest)(nil), "pb.CreateAccountsRequest")
	proto.RegisterType((*CreateAccountsRequest_Request)(nil), "pb.CreateAccountsRequest.Request")
	proto.RegisterType((*CreateAccountsResponse)(nil), "pb.CreateAccountsResponse")
	proto.RegisterType((*CreateAccountsResponse_Response)(nil), "pb.CreateAccountsResponse.Response")
	proto.RegisterType((*CreateControlProgramsRequest)(nil), "pb.CreateControlProgramsRequest")
	proto.RegisterType((*CreateControlProgramsRequest_Account)(nil), "pb.CreateControlProgramsRequest.Account")
	proto.RegisterType((*CreateControlProgramsRequest_Request)(nil), "pb.CreateControlProgramsRequest.Request")
	proto.RegisterType((*CreateControlProgramsResponse)(nil), "pb.CreateControlProgramsResponse")
	proto.RegisterType((*CreateControlProgramsResponse_Response)(nil), "pb.CreateControlProgramsResponse.Response")
	proto.RegisterType((*TxFeed)(nil), "pb.TxFeed")
	proto.RegisterType((*TxFeedResponse)(nil), "pb.TxFeedResponse")
	proto.RegisterType((*CreateTxFeedRequest)(nil), "pb.CreateTxFeedRequest")
	proto.RegisterType((*GetTxFeedRequest)(nil), "pb.GetTxFeedRequest")
	proto.RegisterType((*UpdateTxFeedRequest)(nil), "pb.UpdateTxFeedRequest")
	proto.RegisterType((*DeleteTxFeedRequest)(nil), "pb.DeleteTxFeedRequest")
	proto.RegisterType((*CreateAccessTokenRequest)(nil), "pb.CreateAccessTokenRequest")
	proto.RegisterType((*CreateAccessTokenResponse)(nil), "pb.CreateAccessTokenResponse")
	proto.RegisterType((*ListAccessTokensQuery)(nil), "pb.ListAccessTokensQuery")
	proto.RegisterType((*ListAccessTokensResponse)(nil), "pb.ListAccessTokensResponse")
	proto.RegisterType((*DeleteAccessTokenRequest)(nil), "pb.DeleteAccessTokenRequest")
	proto.RegisterType((*AccessToken)(nil), "pb.AccessToken")
	proto.RegisterType((*FilterParam)(nil), "pb.FilterParam")
	proto.RegisterType((*ListAccountsQuery)(nil), "pb.ListAccountsQuery")
	proto.RegisterType((*ListAccountsResponse)(nil), "pb.ListAccountsResponse")
	proto.RegisterType((*ListAssetsQuery)(nil), "pb.ListAssetsQuery")
	proto.RegisterType((*ListAssetsResponse)(nil), "pb.ListAssetsResponse")
	proto.RegisterType((*ListBalancesQuery)(nil), "pb.ListBalancesQuery")
	proto.RegisterType((*ListBalancesResponse)(nil), "pb.ListBalancesResponse")
	proto.RegisterType((*ListTxFeedsQuery)(nil), "pb.ListTxFeedsQuery")
	proto.RegisterType((*ListTxFeedsResponse)(nil), "pb.ListTxFeedsResponse")
	proto.RegisterType((*ListTxsQuery)(nil), "pb.ListTxsQuery")
	proto.RegisterType((*ListTxsResponse)(nil), "pb.ListTxsResponse")
	proto.RegisterType((*ListUnspentOutputsQuery)(nil), "pb.ListUnspentOutputsQuery")
	proto.RegisterType((*ListUnspentOutputsResponse)(nil), "pb.ListUnspentOutputsResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for App service

type AppClient interface {
	CreateAssets(ctx context.Context, in *CreateAssetsRequest, opts ...grpc.CallOption) (*CreateAssetsResponse, error)
	CreateAccounts(ctx context.Context, in *CreateAccountsRequest, opts ...grpc.CallOption) (*CreateAccountsResponse, error)
	CreateControlPrograms(ctx context.Context, in *CreateControlProgramsRequest, opts ...grpc.CallOption) (*CreateControlProgramsResponse, error)
	CreateTxFeed(ctx context.Context, in *CreateTxFeedRequest, opts ...grpc.CallOption) (*TxFeedResponse, error)
	GetTxFeed(ctx context.Context, in *GetTxFeedRequest, opts ...grpc.CallOption) (*TxFeedResponse, error)
	UpdateTxFeed(ctx context.Context, in *UpdateTxFeedRequest, opts ...grpc.CallOption) (*TxFeedResponse, error)
	DeleteTxFeed(ctx context.Context, in *DeleteTxFeedRequest, opts ...grpc.CallOption) (*ErrorResponse, error)
	CreateAccessToken(ctx context.Context, in *CreateAccessTokenRequest, opts ...grpc.CallOption) (*CreateAccessTokenResponse, error)
	ListAccessTokens(ctx context.Context, in *ListAccessTokensQuery, opts ...grpc.CallOption) (*ListAccessTokensResponse, error)
	DeleteAccessToken(ctx context.Context, in *DeleteAccessTokenRequest, opts ...grpc.CallOption) (*ErrorResponse, error)
	ListAssets(ctx context.Context, in *ListAssetsQuery, opts ...grpc.CallOption) (*ListAssetsResponse, error)
	ListAccounts(ctx context.Context, in *ListAccountsQuery, opts ...grpc.CallOption) (*ListAccountsResponse, error)
	ListBalances(ctx context.Context, in *ListBalancesQuery, opts ...grpc.CallOption) (*ListBalancesResponse, error)
	ListTxFeeds(ctx context.Context, in *ListTxFeedsQuery, opts ...grpc.CallOption) (*ListTxFeedsResponse, error)
	ListTxs(ctx context.Context, in *ListTxsQuery, opts ...grpc.CallOption) (*ListTxsResponse, error)
	ListUnspentOutputs(ctx context.Context, in *ListUnspentOutputsQuery, opts ...grpc.CallOption) (*ListUnspentOutputsResponse, error)
}

type appClient struct {
	cc *grpc.ClientConn
}

func NewAppClient(cc *grpc.ClientConn) AppClient {
	return &appClient{cc}
}

func (c *appClient) CreateAssets(ctx context.Context, in *CreateAssetsRequest, opts ...grpc.CallOption) (*CreateAssetsResponse, error) {
	out := new(CreateAssetsResponse)
	err := grpc.Invoke(ctx, "/pb.App/CreateAssets", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appClient) CreateAccounts(ctx context.Context, in *CreateAccountsRequest, opts ...grpc.CallOption) (*CreateAccountsResponse, error) {
	out := new(CreateAccountsResponse)
	err := grpc.Invoke(ctx, "/pb.App/CreateAccounts", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appClient) CreateControlPrograms(ctx context.Context, in *CreateControlProgramsRequest, opts ...grpc.CallOption) (*CreateControlProgramsResponse, error) {
	out := new(CreateControlProgramsResponse)
	err := grpc.Invoke(ctx, "/pb.App/createControlPrograms", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appClient) CreateTxFeed(ctx context.Context, in *CreateTxFeedRequest, opts ...grpc.CallOption) (*TxFeedResponse, error) {
	out := new(TxFeedResponse)
	err := grpc.Invoke(ctx, "/pb.App/CreateTxFeed", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appClient) GetTxFeed(ctx context.Context, in *GetTxFeedRequest, opts ...grpc.CallOption) (*TxFeedResponse, error) {
	out := new(TxFeedResponse)
	err := grpc.Invoke(ctx, "/pb.App/GetTxFeed", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appClient) UpdateTxFeed(ctx context.Context, in *UpdateTxFeedRequest, opts ...grpc.CallOption) (*TxFeedResponse, error) {
	out := new(TxFeedResponse)
	err := grpc.Invoke(ctx, "/pb.App/UpdateTxFeed", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appClient) DeleteTxFeed(ctx context.Context, in *DeleteTxFeedRequest, opts ...grpc.CallOption) (*ErrorResponse, error) {
	out := new(ErrorResponse)
	err := grpc.Invoke(ctx, "/pb.App/DeleteTxFeed", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appClient) CreateAccessToken(ctx context.Context, in *CreateAccessTokenRequest, opts ...grpc.CallOption) (*CreateAccessTokenResponse, error) {
	out := new(CreateAccessTokenResponse)
	err := grpc.Invoke(ctx, "/pb.App/CreateAccessToken", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appClient) ListAccessTokens(ctx context.Context, in *ListAccessTokensQuery, opts ...grpc.CallOption) (*ListAccessTokensResponse, error) {
	out := new(ListAccessTokensResponse)
	err := grpc.Invoke(ctx, "/pb.App/ListAccessTokens", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appClient) DeleteAccessToken(ctx context.Context, in *DeleteAccessTokenRequest, opts ...grpc.CallOption) (*ErrorResponse, error) {
	out := new(ErrorResponse)
	err := grpc.Invoke(ctx, "/pb.App/DeleteAccessToken", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appClient) ListAssets(ctx context.Context, in *ListAssetsQuery, opts ...grpc.CallOption) (*ListAssetsResponse, error) {
	out := new(ListAssetsResponse)
	err := grpc.Invoke(ctx, "/pb.App/ListAssets", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appClient) ListAccounts(ctx context.Context, in *ListAccountsQuery, opts ...grpc.CallOption) (*ListAccountsResponse, error) {
	out := new(ListAccountsResponse)
	err := grpc.Invoke(ctx, "/pb.App/ListAccounts", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appClient) ListBalances(ctx context.Context, in *ListBalancesQuery, opts ...grpc.CallOption) (*ListBalancesResponse, error) {
	out := new(ListBalancesResponse)
	err := grpc.Invoke(ctx, "/pb.App/ListBalances", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appClient) ListTxFeeds(ctx context.Context, in *ListTxFeedsQuery, opts ...grpc.CallOption) (*ListTxFeedsResponse, error) {
	out := new(ListTxFeedsResponse)
	err := grpc.Invoke(ctx, "/pb.App/ListTxFeeds", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appClient) ListTxs(ctx context.Context, in *ListTxsQuery, opts ...grpc.CallOption) (*ListTxsResponse, error) {
	out := new(ListTxsResponse)
	err := grpc.Invoke(ctx, "/pb.App/ListTxs", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appClient) ListUnspentOutputs(ctx context.Context, in *ListUnspentOutputsQuery, opts ...grpc.CallOption) (*ListUnspentOutputsResponse, error) {
	out := new(ListUnspentOutputsResponse)
	err := grpc.Invoke(ctx, "/pb.App/ListUnspentOutputs", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for App service

type AppServer interface {
	CreateAssets(context.Context, *CreateAssetsRequest) (*CreateAssetsResponse, error)
	CreateAccounts(context.Context, *CreateAccountsRequest) (*CreateAccountsResponse, error)
	CreateControlPrograms(context.Context, *CreateControlProgramsRequest) (*CreateControlProgramsResponse, error)
	CreateTxFeed(context.Context, *CreateTxFeedRequest) (*TxFeedResponse, error)
	GetTxFeed(context.Context, *GetTxFeedRequest) (*TxFeedResponse, error)
	UpdateTxFeed(context.Context, *UpdateTxFeedRequest) (*TxFeedResponse, error)
	DeleteTxFeed(context.Context, *DeleteTxFeedRequest) (*ErrorResponse, error)
	CreateAccessToken(context.Context, *CreateAccessTokenRequest) (*CreateAccessTokenResponse, error)
	ListAccessTokens(context.Context, *ListAccessTokensQuery) (*ListAccessTokensResponse, error)
	DeleteAccessToken(context.Context, *DeleteAccessTokenRequest) (*ErrorResponse, error)
	ListAssets(context.Context, *ListAssetsQuery) (*ListAssetsResponse, error)
	ListAccounts(context.Context, *ListAccountsQuery) (*ListAccountsResponse, error)
	ListBalances(context.Context, *ListBalancesQuery) (*ListBalancesResponse, error)
	ListTxFeeds(context.Context, *ListTxFeedsQuery) (*ListTxFeedsResponse, error)
	ListTxs(context.Context, *ListTxsQuery) (*ListTxsResponse, error)
	ListUnspentOutputs(context.Context, *ListUnspentOutputsQuery) (*ListUnspentOutputsResponse, error)
}

func RegisterAppServer(s *grpc.Server, srv AppServer) {
	s.RegisterService(&_App_serviceDesc, srv)
}

func _App_CreateAssets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAssetsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppServer).CreateAssets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.App/CreateAssets",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppServer).CreateAssets(ctx, req.(*CreateAssetsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _App_CreateAccounts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAccountsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppServer).CreateAccounts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.App/CreateAccounts",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppServer).CreateAccounts(ctx, req.(*CreateAccountsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _App_CreateControlPrograms_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateControlProgramsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppServer).CreateControlPrograms(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.App/CreateControlPrograms",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppServer).CreateControlPrograms(ctx, req.(*CreateControlProgramsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _App_CreateTxFeed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTxFeedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppServer).CreateTxFeed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.App/CreateTxFeed",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppServer).CreateTxFeed(ctx, req.(*CreateTxFeedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _App_GetTxFeed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTxFeedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppServer).GetTxFeed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.App/GetTxFeed",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppServer).GetTxFeed(ctx, req.(*GetTxFeedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _App_UpdateTxFeed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateTxFeedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppServer).UpdateTxFeed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.App/UpdateTxFeed",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppServer).UpdateTxFeed(ctx, req.(*UpdateTxFeedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _App_DeleteTxFeed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteTxFeedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppServer).DeleteTxFeed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.App/DeleteTxFeed",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppServer).DeleteTxFeed(ctx, req.(*DeleteTxFeedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _App_CreateAccessToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAccessTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppServer).CreateAccessToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.App/CreateAccessToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppServer).CreateAccessToken(ctx, req.(*CreateAccessTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _App_ListAccessTokens_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAccessTokensQuery)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppServer).ListAccessTokens(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.App/ListAccessTokens",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppServer).ListAccessTokens(ctx, req.(*ListAccessTokensQuery))
	}
	return interceptor(ctx, in, info, handler)
}

func _App_DeleteAccessToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteAccessTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppServer).DeleteAccessToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.App/DeleteAccessToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppServer).DeleteAccessToken(ctx, req.(*DeleteAccessTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _App_ListAssets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAssetsQuery)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppServer).ListAssets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.App/ListAssets",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppServer).ListAssets(ctx, req.(*ListAssetsQuery))
	}
	return interceptor(ctx, in, info, handler)
}

func _App_ListAccounts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAccountsQuery)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppServer).ListAccounts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.App/ListAccounts",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppServer).ListAccounts(ctx, req.(*ListAccountsQuery))
	}
	return interceptor(ctx, in, info, handler)
}

func _App_ListBalances_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListBalancesQuery)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppServer).ListBalances(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.App/ListBalances",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppServer).ListBalances(ctx, req.(*ListBalancesQuery))
	}
	return interceptor(ctx, in, info, handler)
}

func _App_ListTxFeeds_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTxFeedsQuery)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppServer).ListTxFeeds(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.App/ListTxFeeds",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppServer).ListTxFeeds(ctx, req.(*ListTxFeedsQuery))
	}
	return interceptor(ctx, in, info, handler)
}

func _App_ListTxs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTxsQuery)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppServer).ListTxs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.App/ListTxs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppServer).ListTxs(ctx, req.(*ListTxsQuery))
	}
	return interceptor(ctx, in, info, handler)
}

func _App_ListUnspentOutputs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListUnspentOutputsQuery)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppServer).ListUnspentOutputs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.App/ListUnspentOutputs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppServer).ListUnspentOutputs(ctx, req.(*ListUnspentOutputsQuery))
	}
	return interceptor(ctx, in, info, handler)
}

var _App_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.App",
	HandlerType: (*AppServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateAssets",
			Handler:    _App_CreateAssets_Handler,
		},
		{
			MethodName: "CreateAccounts",
			Handler:    _App_CreateAccounts_Handler,
		},
		{
			MethodName: "createControlPrograms",
			Handler:    _App_CreateControlPrograms_Handler,
		},
		{
			MethodName: "CreateTxFeed",
			Handler:    _App_CreateTxFeed_Handler,
		},
		{
			MethodName: "GetTxFeed",
			Handler:    _App_GetTxFeed_Handler,
		},
		{
			MethodName: "UpdateTxFeed",
			Handler:    _App_UpdateTxFeed_Handler,
		},
		{
			MethodName: "DeleteTxFeed",
			Handler:    _App_DeleteTxFeed_Handler,
		},
		{
			MethodName: "CreateAccessToken",
			Handler:    _App_CreateAccessToken_Handler,
		},
		{
			MethodName: "ListAccessTokens",
			Handler:    _App_ListAccessTokens_Handler,
		},
		{
			MethodName: "DeleteAccessToken",
			Handler:    _App_DeleteAccessToken_Handler,
		},
		{
			MethodName: "ListAssets",
			Handler:    _App_ListAssets_Handler,
		},
		{
			MethodName: "ListAccounts",
			Handler:    _App_ListAccounts_Handler,
		},
		{
			MethodName: "ListBalances",
			Handler:    _App_ListBalances_Handler,
		},
		{
			MethodName: "ListTxFeeds",
			Handler:    _App_ListTxFeeds_Handler,
		},
		{
			MethodName: "ListTxs",
			Handler:    _App_ListTxs_Handler,
		},
		{
			MethodName: "ListUnspentOutputs",
			Handler:    _App_ListUnspentOutputs_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "app.proto",
}

func init() { proto.RegisterFile("app.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 1753 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xbc, 0x59, 0x4f, 0x6f, 0xdb, 0xc8,
	0x15, 0x17, 0xf5, 0x5f, 0x4f, 0xf2, 0xbf, 0xb1, 0x65, 0xd3, 0x8c, 0x1d, 0xcb, 0x4a, 0xd3, 0x28,
	0x01, 0xea, 0x02, 0x6e, 0x90, 0x1c, 0xd2, 0xa4, 0x90, 0xe3, 0xa6, 0x4e, 0xe3, 0xa0, 0x2e, 0xe3,
	0x20, 0x2d, 0x50, 0x84, 0xa0, 0xa4, 0x91, 0x4c, 0x84, 0x22, 0x19, 0x72, 0xe8, 0x58, 0x01, 0x7a,
	0xe9, 0xb1, 0x45, 0x0f, 0x3d, 0xb4, 0x97, 0x02, 0xbb, 0xd8, 0x0f, 0xb0, 0xfb, 0x31, 0xf6, 0xbc,
	0x5f, 0x60, 0x81, 0xdd, 0xcb, 0x7e, 0x8d, 0x2c, 0x66, 0x86, 0x7f, 0x86, 0x12, 0x65, 0x69, 0xd7,
	0x48, 0x4e, 0xe6, 0xbc, 0x37, 0x6f, 0xde, 0x7b, 0xbf, 0xf7, 0x9b, 0x37, 0x33, 0x32, 0x54, 0x74,
	0xc7, 0xd9, 0x73, 0x5c, 0x9b, 0xd8, 0x28, 0xeb, 0x74, 0x94, 0x5a, 0xd7, 0x1e, 0x0e, 0x6d, 0x8b,
	0x4b, 0x9a, 0xdf, 0x66, 0xa1, 0xd0, 0xf6, 0x3c, 0x4c, 0xd0, 0x22, 0x64, 0x8d, 0x9e, 0x2c, 0x35,
	0xa4, 0x56, 0x45, 0xcd, 0x1a, 0x3d, 0xb4, 0x06, 0x05, 0xdd, 0x34, 0x74, 0x4f, 0xce, 0x32, 0x11,
	0x1f, 0xa0, 0xdb, 0xb0, 0x6c, 0x78, 0x9e, 0xaf, 0x5b, 0x5d, 0xac, 0x39, 0xae, 0x3d, 0x70, 0xf5,
	0xa1, 0x9c, 0x6b, 0x48, 0xad, 0x9a, 0xba, 0x14, 0xca, 0x4f, 0xb8, 0x18, 0xed, 0x42, 0xfe, 0x0d,
	0x1e, 0x79, 0x72, 0xbe, 0x91, 0x6b, 0x55, 0xf7, 0x17, 0xf6, 0x9c, 0xce, 0x1e, 0xf3, 0xb4, 0xf7,
	0x0c, 0x8f, 0x54, 0xa6, 0x42, 0xeb, 0x50, 0x7c, 0xeb, 0xdb, 0xae, 0x3f, 0x94, 0x0b, 0x0d, 0xa9,
	0x55, 0x50, 0x83, 0x11, 0xba, 0x0e, 0xd0, 0xc3, 0x7d, 0xc3, 0x32, 0x88, 0x61, 0x5b, 0x72, 0x91,
	0xad, 0x2f, 0x48, 0x10, 0x82, 0x3c, 0xd1, 0x07, 0x9e, 0x5c, 0x62, 0x1a, 0xf6, 0x8d, 0x36, 0xa1,
	0x6c, 0x78, 0x9a, 0x69, 0x77, 0x75, 0x53, 0x2e, 0x37, 0xa4, 0x56, 0x59, 0x2d, 0x19, 0xde, 0x31,
	0x1d, 0x2a, 0x23, 0xc8, 0x3d, 0xc3, 0x23, 0x74, 0x0d, 0x2a, 0xae, 0x6d, 0x13, 0xed, 0xc2, 0xf1,
	0x3b, 0x2c, 0xd1, 0x9a, 0x5a, 0xa6, 0x82, 0xbf, 0x38, 0x7e, 0x07, 0xed, 0x42, 0x4d, 0xa7, 0xd1,
	0x69, 0x8e, 0xdf, 0x79, 0x83, 0x47, 0x2c, 0xeb, 0x9a, 0x5a, 0x65, 0xb2, 0x13, 0x26, 0x42, 0xfb,
	0x50, 0xe7, 0x53, 0x7a, 0xd8, 0x35, 0xce, 0x75, 0x1a, 0x89, 0xe6, 0xe8, 0xe4, 0x4c, 0xce, 0x35,
	0x72, 0xad, 0x9a, 0xba, 0xca, 0x94, 0x87, 0x91, 0xee, 0x44, 0x27, 0x67, 0xcd, 0x7f, 0x64, 0x61,
	0xf5, 0xb1, 0x8b, 0x75, 0x82, 0x59, 0xee, 0x9e, 0x8a, 0xdf, 0xfa, 0xd8, 0x23, 0xe8, 0x01, 0x94,
	0x5d, 0xfe, 0xe9, 0xc9, 0x12, 0x03, 0x68, 0x87, 0x02, 0x94, 0x32, 0x75, 0x2f, 0xf8, 0xab, 0x46,
	0x06, 0xca, 0x97, 0x12, 0x94, 0xc2, 0x85, 0xa2, 0x32, 0x49, 0x62, 0x99, 0xb6, 0x01, 0xa2, 0x54,
	0x69, 0x05, 0x73, 0xad, 0x8a, 0x5a, 0x09, 0x73, 0x15, 0x71, 0xcf, 0x5d, 0x82, 0x7b, 0x7e, 0x2a,
	0xee, 0x05, 0x01, 0xf7, 0x5d, 0xa8, 0x75, 0x4d, 0x03, 0x5b, 0x44, 0x23, 0xf6, 0x1b, 0xcc, 0xab,
	0x55, 0x51, 0xab, 0x5c, 0x76, 0x4a, 0x45, 0xcd, 0xaf, 0x25, 0x58, 0x4b, 0x66, 0xe6, 0x39, 0xb6,
	0xe5, 0x61, 0xf4, 0x3b, 0xa8, 0xb8, 0xc1, 0x77, 0x08, 0xc3, 0xee, 0x24, 0x0c, 0x7c, 0xc2, 0x5e,
	0xf8, 0xa1, 0xc6, 0x36, 0x68, 0x07, 0x0a, 0xd8, 0x75, 0x6d, 0x57, 0xae, 0x34, 0xa4, 0x56, 0x75,
	0xbf, 0x42, 0x8d, 0x7f, 0x4f, 0x05, 0x2a, 0x97, 0x2b, 0xc7, 0x50, 0x8e, 0xbc, 0xed, 0x40, 0x81,
	0x95, 0x88, 0x41, 0x15, 0x4c, 0x66, 0x3e, 0x54, 0x2e, 0x9f, 0xb9, 0x5a, 0xf3, 0x83, 0x04, 0xa5,
	0x76, 0xb7, 0x6b, 0xfb, 0xd6, 0xbc, 0xfb, 0xe5, 0x46, 0xb0, 0x09, 0x72, 0x2c, 0xb9, 0x25, 0xe6,
	0x92, 0x2f, 0x90, 0xba, 0x0d, 0xf2, 0x89, 0x72, 0xa4, 0xc0, 0xad, 0xfc, 0x7d, 0x4e, 0x2e, 0x73,
	0x27, 0x5c, 0x1f, 0x72, 0x99, 0xcb, 0xd8, 0x94, 0x7b, 0xb0, 0x11, 0x4e, 0x49, 0x67, 0x73, 0x3d,
	0x50, 0x8f, 0xf1, 0xf9, 0x07, 0x09, 0xea, 0x41, 0x75, 0xb8, 0x3e, 0x62, 0xf4, 0xc3, 0x09, 0x46,
	0x8b, 0xa5, 0x4c, 0x4e, 0x4e, 0xe1, 0xf4, 0xbf, 0x05, 0x4e, 0x27, 0xd9, 0x2b, 0x4d, 0x67, 0x6f,
	0x36, 0x01, 0x57, 0x54, 0x81, 0x9c, 0x58, 0x81, 0x10, 0xc4, 0xfc, 0x25, 0x9c, 0x2d, 0x4c, 0x72,
	0xf6, 0x1b, 0x09, 0xd6, 0xc7, 0x63, 0x0f, 0x78, 0xd4, 0x9e, 0x64, 0xed, 0x8d, 0xb4, 0x54, 0xaf,
	0xc2, 0x5b, 0x55, 0xe0, 0xed, 0x4d, 0x28, 0x05, 0xc5, 0x08, 0x98, 0x5b, 0x15, 0x68, 0xa4, 0x86,
	0xba, 0xd9, 0xec, 0xfd, 0x2c, 0x0b, 0x5b, 0x3c, 0xc6, 0xc7, 0xb6, 0x45, 0x5c, 0xdb, 0x0c, 0x3a,
	0x75, 0x54, 0xc2, 0xc3, 0x89, 0x12, 0xb6, 0xe2, 0xbc, 0xd2, 0x6d, 0x52, 0x2a, 0xa9, 0xc5, 0x7b,
	0x64, 0x07, 0x20, 0x64, 0x59, 0xb8, 0x57, 0x8e, 0x32, 0x6a, 0x25, 0x90, 0x3d, 0xed, 0xa1, 0x9b,
	0xb0, 0x10, 0x4e, 0x10, 0x36, 0xcf, 0x51, 0x46, 0x0d, 0x09, 0xdc, 0xa6, 0xd2, 0x83, 0x1a, 0x80,
	0xd1, 0xc3, 0x16, 0x31, 0xfa, 0x06, 0x76, 0x95, 0x57, 0x31, 0x53, 0x0e, 0xc7, 0xa1, 0x99, 0x1d,
	0x70, 0x10, 0xdb, 0x51, 0x26, 0x42, 0xee, 0xa0, 0x08, 0x79, 0x32, 0x72, 0x70, 0xf3, 0x3b, 0x09,
	0xb6, 0xa7, 0xd8, 0x06, 0xa5, 0x38, 0x9a, 0x2c, 0xfd, 0x9d, 0x4b, 0x3c, 0x5e, 0x85, 0x01, 0xa7,
	0x02, 0x03, 0x6e, 0xc1, 0x52, 0x97, 0xaf, 0x1d, 0x1d, 0xba, 0x7c, 0xcf, 0x2f, 0x76, 0x13, 0x2e,
	0x67, 0x73, 0xe0, 0x6f, 0x50, 0x3c, 0xbd, 0x78, 0x82, 0x71, 0x6f, 0xce, 0xfe, 0xb5, 0x0e, 0xc5,
	0xbe, 0x61, 0x12, 0xec, 0x06, 0x9b, 0x2a, 0x18, 0xb1, 0xd9, 0x7d, 0x2a, 0xce, 0x07, 0xb3, 0xe9,
	0xa0, 0xf9, 0x57, 0x58, 0xe4, 0xab, 0x47, 0x91, 0xff, 0x92, 0x52, 0x8a, 0x7f, 0x07, 0x15, 0x02,
	0x1a, 0x53, 0x30, 0x2b, 0xd2, 0xcd, 0x0e, 0xbc, 0x1f, 0x9e, 0xa3, 0xa1, 0x83, 0xcb, 0x8e, 0xbf,
	0x38, 0xea, 0x6c, 0x22, 0xea, 0xf1, 0x7d, 0x9f, 0x9b, 0xdc, 0xf7, 0x7f, 0x84, 0xe5, 0x3f, 0x60,
	0x92, 0x74, 0xb2, 0x1c, 0x43, 0x75, 0x94, 0x61, 0x60, 0xad, 0x27, 0xc0, 0x3a, 0xca, 0x04, 0x8e,
	0x93, 0x44, 0x6d, 0xfe, 0x53, 0x82, 0xd5, 0x97, 0x4e, 0x6f, 0x22, 0xe8, 0xb9, 0xd7, 0x43, 0x37,
	0x61, 0xd1, 0x71, 0xf1, 0xb9, 0x61, 0xfb, 0x9e, 0xc6, 0xf1, 0xe6, 0x21, 0x2f, 0x84, 0xd2, 0x76,
	0x7f, 0x6a, 0x35, 0xc6, 0x82, 0x79, 0x0e, 0xab, 0x87, 0xd8, 0xc4, 0x3f, 0x3b, 0x96, 0xb1, 0xe5,
	0x1e, 0x81, 0x1c, 0xf5, 0x3b, 0xec, 0x79, 0x0c, 0xbc, 0x70, 0xcd, 0x71, 0x6a, 0x21, 0xbe, 0xbf,
	0x82, 0x62, 0xf0, 0xbd, 0xd6, 0x85, 0xcd, 0x14, 0xfb, 0xa8, 0xe3, 0x15, 0x78, 0x81, 0x38, 0x65,
	0xc2, 0x63, 0x33, 0x9a, 0xc7, 0xb5, 0xb3, 0x49, 0xf3, 0x1a, 0xea, 0xc7, 0x86, 0x47, 0x04, 0x53,
	0xef, 0xcf, 0x3e, 0x76, 0x47, 0x51, 0x44, 0x52, 0x1c, 0x11, 0x3d, 0x52, 0x1d, 0x7d, 0x80, 0x35,
	0xcf, 0x78, 0x8f, 0x83, 0x93, 0xa5, 0x4c, 0x05, 0x2f, 0x8c, 0xf7, 0x38, 0x46, 0x38, 0x27, 0xf2,
	0xfd, 0x2b, 0x09, 0xe4, 0x71, 0x07, 0x62, 0x12, 0x06, 0xc1, 0xc3, 0xb0, 0x4f, 0x4c, 0x26, 0xc1,
	0xb4, 0xd4, 0xad, 0xa9, 0x7b, 0x44, 0xa3, 0xae, 0x98, 0xdb, 0xb2, 0x5a, 0xa6, 0x82, 0x13, 0x7d,
	0x80, 0xd1, 0xaf, 0x20, 0x6f, 0xe1, 0x0b, 0xc2, 0xbc, 0x56, 0xf7, 0x37, 0xe9, 0x12, 0xa9, 0x09,
	0xa9, 0x6c, 0xda, 0x6c, 0x40, 0xee, 0x80, 0xcc, 0x49, 0x30, 0xbb, 0x6a, 0xcd, 0x3e, 0x54, 0x85,
	0x59, 0x69, 0xfd, 0x82, 0xd7, 0x28, 0xe8, 0x17, 0xbc, 0x24, 0x21, 0xb0, 0x39, 0x01, 0xd8, 0x6d,
	0x80, 0x2e, 0x2b, 0x75, 0x4f, 0xd3, 0x49, 0x40, 0xd1, 0x4a, 0x20, 0x69, 0x93, 0xe6, 0x39, 0x54,
	0x9f, 0xb0, 0xed, 0x79, 0xa2, 0xd3, 0x16, 0x26, 0x43, 0xd1, 0x23, 0xae, 0x61, 0x0d, 0x22, 0x52,
	0x06, 0x63, 0x4a, 0x4c, 0xc3, 0x22, 0xf7, 0xee, 0x32, 0x8f, 0x39, 0x4a, 0x4c, 0x36, 0xa4, 0xf2,
	0xce, 0x88, 0x60, 0x7e, 0xee, 0xd7, 0xa8, 0x9c, 0x0d, 0xd1, 0x1a, 0xe4, 0x3b, 0xb6, 0x6d, 0x32,
	0x8f, 0xe5, 0xa3, 0x8c, 0xca, 0x46, 0x07, 0x25, 0x28, 0x9c, 0xeb, 0xa6, 0x8f, 0x9b, 0xef, 0x60,
	0x25, 0xc0, 0x92, 0x9d, 0xd7, 0x9c, 0x18, 0x71, 0xe7, 0x90, 0x12, 0x9d, 0xe3, 0x2e, 0x2c, 0xf0,
	0x2f, 0xcd, 0xa1, 0x51, 0xf2, 0x3b, 0x75, 0x50, 0x54, 0x21, 0x7a, 0xb5, 0xd6, 0x8f, 0x07, 0xde,
	0x14, 0xd6, 0xfc, 0x57, 0x82, 0x35, 0xd1, 0x73, 0xc4, 0x98, 0xb5, 0x98, 0x31, 0xb4, 0xb9, 0xcf,
	0x43, 0x90, 0xdb, 0x09, 0x82, 0xd4, 0x05, 0x82, 0xc4, 0x49, 0xcd, 0x4b, 0x0e, 0x1f, 0x96, 0x98,
	0x2d, 0xbb, 0x76, 0x7f, 0x3a, 0x38, 0xfe, 0x23, 0x01, 0x8a, 0xfd, 0x5e, 0x05, 0x8c, 0x5b, 0x09,
	0x30, 0x56, 0x23, 0x30, 0xe2, 0x84, 0xe6, 0x85, 0xe2, 0x7f, 0x12, 0x27, 0xc7, 0x81, 0x6e, 0xd2,
	0x27, 0xed, 0x47, 0x41, 0xa3, 0x0e, 0x45, 0xcf, 0x1f, 0x6a, 0x9d, 0x11, 0xbb, 0x71, 0x57, 0xd4,
	0x82, 0xe7, 0x0f, 0x0f, 0x46, 0x68, 0x0b, 0x2a, 0xc4, 0x18, 0x62, 0x8f, 0xe8, 0x43, 0x87, 0x51,
	0x37, 0xaf, 0xc6, 0x82, 0x88, 0x3b, 0x61, 0x60, 0x1f, 0x81, 0x3b, 0x89, 0x9c, 0xe7, 0x05, 0xac,
	0x05, 0xcb, 0xd4, 0x96, 0x9f, 0x2d, 0x01, 0x5c, 0x51, 0xb9, 0x25, 0xb1, 0xdc, 0x9f, 0x4b, 0xb0,
	0x2a, 0x4c, 0x8d, 0x12, 0x68, 0x24, 0xdb, 0xa5, 0x78, 0x4d, 0x98, 0x27, 0x99, 0x56, 0x22, 0x99,
	0xb5, 0x30, 0x19, 0x31, 0xa0, 0x79, 0x73, 0xf9, 0x20, 0x41, 0x8d, 0xdb, 0x7e, 0x94, 0xba, 0xdf,
	0x07, 0x59, 0xf7, 0xba, 0xd8, 0xea, 0x19, 0xd6, 0x40, 0x7b, 0x67, 0x90, 0x33, 0xcd, 0xb4, 0xad,
	0x81, 0xe6, 0xd8, 0xa6, 0xc9, 0xa2, 0x2f, 0xab, 0xf5, 0x48, 0xff, 0xca, 0x20, 0x67, 0xc7, 0xb6,
	0x35, 0x38, 0xb1, 0x4d, 0x13, 0xc9, 0x50, 0xa2, 0x44, 0xb0, 0xfd, 0xb0, 0x89, 0x86, 0x43, 0xda,
	0x61, 0x3d, 0xa2, 0xbb, 0x44, 0xa3, 0x02, 0xf6, 0x9a, 0xc9, 0xab, 0x15, 0x26, 0x39, 0x35, 0x86,
	0x18, 0x6d, 0x42, 0x19, 0x5b, 0x3d, 0xae, 0x2c, 0x32, 0x65, 0x09, 0x5b, 0x3d, 0xa6, 0x8a, 0x6a,
	0x54, 0x12, 0x6b, 0xf4, 0x2f, 0x89, 0xb7, 0x82, 0xd3, 0x8b, 0x2b, 0x11, 0xec, 0x17, 0x89, 0x9a,
	0x2c, 0xc7, 0x35, 0xf9, 0x69, 0xf5, 0xf8, 0xbf, 0x04, 0x1b, 0xd4, 0xee, 0xa5, 0xe5, 0x39, 0xd8,
	0x22, 0x7f, 0xf2, 0x89, 0xe3, 0x7f, 0xc2, 0x06, 0x35, 0x63, 0x47, 0x7e, 0x21, 0x81, 0x32, 0x19,
	0xdd, 0x55, 0x60, 0xfb, 0x75, 0x02, 0xb6, 0x6b, 0x21, 0x6c, 0x29, 0xe9, 0xcf, 0x89, 0xe0, 0xfe,
	0xf7, 0x65, 0xc8, 0xb5, 0x1d, 0x07, 0x3d, 0x86, 0x9a, 0xf8, 0xd3, 0x0a, 0xda, 0x98, 0xf2, 0x9b,
	0x93, 0x22, 0x4f, 0xfb, 0x15, 0xa6, 0x99, 0x41, 0x4f, 0x61, 0x31, 0xf9, 0xd2, 0x45, 0x9b, 0x53,
	0x1f, 0xfa, 0x8a, 0x32, 0xfd, 0x61, 0xdc, 0xcc, 0xa0, 0xd7, 0x50, 0xef, 0xa6, 0xbd, 0x9c, 0x50,
	0x63, 0xd6, 0x33, 0x4e, 0xd9, 0x9d, 0xf9, 0xec, 0x6a, 0x66, 0xd0, 0xc3, 0x30, 0xdf, 0xe0, 0xcd,
	0x23, 0xe4, 0x9b, 0xb8, 0x05, 0x2b, 0x48, 0xe8, 0x36, 0xb1, 0xf9, 0x7d, 0xa8, 0x44, 0x6f, 0x01,
	0xc4, 0x5a, 0xca, 0xf8, 0xd3, 0x60, 0x8a, 0xe1, 0x43, 0xa8, 0x89, 0xf7, 0x7e, 0xee, 0x37, 0xe5,
	0x25, 0x30, 0xc5, 0xfc, 0xb7, 0x50, 0x13, 0xaf, 0xea, 0xdc, 0x3c, 0xe5, 0xf2, 0xae, 0xac, 0xc4,
	0x95, 0x8e, 0xad, 0x55, 0x58, 0x99, 0xb8, 0x59, 0xa3, 0xad, 0x44, 0x1d, 0xc6, 0xae, 0x7e, 0xca,
	0xf6, 0x14, 0x6d, 0xb4, 0xe6, 0x73, 0xde, 0xde, 0xc5, 0x7b, 0x27, 0x9a, 0x7e, 0x1b, 0x55, 0xb6,
	0xd2, 0x54, 0xc2, 0x72, 0x4f, 0x60, 0x65, 0xe2, 0x1a, 0xca, 0x43, 0x9c, 0x76, 0x3b, 0x4d, 0x4f,
	0xf5, 0x01, 0x40, 0x7c, 0xc0, 0xa3, 0xb4, 0x03, 0x5f, 0x59, 0x4f, 0x0a, 0x05, 0xe3, 0x36, 0xef,
	0xf2, 0x11, 0x8b, 0xd3, 0x2f, 0x4f, 0x7c, 0x2b, 0xa4, 0x5d, 0xd7, 0xe2, 0x25, 0xc2, 0x13, 0x13,
	0xa5, 0x9f, 0xa1, 0xf1, 0x12, 0xe3, 0xa7, 0x76, 0x33, 0x83, 0x1e, 0x41, 0x55, 0x38, 0xa7, 0x50,
	0xea, 0xc1, 0xa5, 0x6c, 0x8c, 0x49, 0x05, 0xfb, 0x7d, 0x28, 0x05, 0x3d, 0x15, 0x4d, 0x34, 0x58,
	0x65, 0x55, 0x90, 0x08, 0x36, 0x2f, 0xf8, 0x85, 0x2b, 0xd9, 0x50, 0xd0, 0x65, 0x8d, 0x46, 0xb9,
	0x9e, 0xae, 0x8c, 0x17, 0xed, 0x14, 0xd9, 0x3f, 0x14, 0x7e, 0xf3, 0x63, 0x00, 0x00, 0x00, 0xff,
	0xff, 0xa1, 0x21, 0x06, 0xca, 0x6f, 0x18, 0x00, 0x00,
}
